import { StyleSheet } from 'react-native';

export const answerPostStyle = StyleSheet.create({
    answerInputContainer: {
        backgroundColor: '#fff',
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 20,
        paddingRight: 20,
        borderTopWidth: 1,
        borderTopColor: '#E8E8E8',
    },
    replyModeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
        marginBottom: 10,
        borderWidth: 0.5,
        borderColor: '#E8E8E8',
    },
    replyModeText: {
        fontSize: 12,
        fontFamily: 'SUIT-Medium',
        color: '#666',
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 15,
    },
    userIconContainer: {
        width: 30,
        height: 30,
        marginRight: 8,
        borderRadius: 15,
        overflow: 'hidden',
    },
    userIconSmall: {
        backgroundColor: '#f1f3f4',
        borderRadius: 15,
        width: 30,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    answerInput: {
        flex: 1,
        padding: 10,
        fontSize: 14,
        fontFamily: 'SUIT-Regular',
        letterSpacing: -0.35,
        color: '#666',
        minHeight: 40,
        maxHeight: 100,
    },
    inputActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    aiAnswerButton: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        borderWidth: 0.5,
        borderColor: '#E8E8E8',
    },
    aiAnswerButtonText: {
        fontSize: 14,
        fontFamily: 'SUIT-Regular',
        letterSpacing: -0.35,
        color: '#4B4B4B',
        marginLeft: 5,
    },
    submitButton: {
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        borderWidth: 0.5,
        borderColor: '#E8E8E8',
    },
    submitButtonDisabled: {
        opacity: 0.6,
    },
    submitButtonText: {
        fontSize: 14,
        fontFamily: 'SUIT-Regular',
        letterSpacing: -0.35,
        color: '#4B4B4B',
    },
    // AI 답변 생성 관련
    aiGeneratingContainer: {
        paddingVertical: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    aiGeneratingText: {
        marginTop: 12,
        fontSize: 16,
        color: '#666666',
        fontFamily: 'SUIT-Medium',
    },
    aiAnswerPreviewContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        padding: 15,
        marginVertical: 10,
        borderWidth: 0.5,
        borderColor: '#E8E8E8',
    },
    aiAnswerHeader: {
        marginBottom: 10,
    },
    aiAnswerIconContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    aiIcon: {
        backgroundColor: '#333',
        borderRadius: 15,
        width: 30,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 8,
    },
    aiIconText: {
        color: '#fff',
        fontSize: 10,
    },
    aiAnswerAuthor: {
        fontSize: 11,
        fontFamily: 'SUIT-Medium',
        color: '#666',
    },
    aiAnswerContent: {
        fontSize: 13,
        fontFamily: 'SUIT-Medium',
        letterSpacing: -0.3,
        lineHeight: 18,
        color: '#666',
        marginBottom: 15,
    },
    aiAnswerActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 8,
    },
    aiCancelButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        borderWidth: 0.5,
        borderColor: '#E8E8E8',
    },
    aiCancelButtonText: {
        fontSize: 14,
        fontFamily: 'SUIT-Regular',
        letterSpacing: -0.35,
        color: '#999999',
    },
    aiSubmitButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        borderWidth: 0.5,
        borderColor: '#E8E8E8',
    },
    aiSubmitButtonDisabled: {
        opacity: 0.6,
    },
    aiSubmitButtonText: {
        fontSize: 14,
        fontFamily: 'SUIT-Regular',
        letterSpacing: -0.35,
        color: '#4B4B4B',
    },
});