import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E8E8',
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rightSection: {
    position: 'relative',
    padding: 4,
  },
  badge: {
    position: 'absolute',
    top: 6,
    right: 8,
    width: 5.71,
    height: 5.71,
    borderRadius: 4,
    backgroundColor: '#90D1BE',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  recommendationCard: {
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#0D2525',
    padding: 18,
    marginVertical: 24,
  },
  recommendationText: {
    fontSize: 14,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 17,
  },
  highlightText: {
    color: '#0D2525',
    fontWeight: 'bold',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  statItem: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: 15,
    fontWeight: '500',
    color: '#666666',
  },
  statValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#4b4b4b',
    marginHorizontal: 17,
  },
  tooltip: {
    position: 'absolute',
    bottom: -55, 
    left: 20,
    right: 20,
    backgroundColor: '#DFDFDF',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tooltipText: {
    fontFamily: 'SUIT-Medium',
    fontSize: 12,
    color: '#4B4B4B',
    textAlign: 'center',
    fontWeight: '500',
  },
  sectionHeader: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 13,
    paddingBottom: 13,
    paddingLeft: 20,
    paddingRight: 20,
    borderTopWidth: 0.5,
    borderTopColor: '#E8E8E8',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E8E8E8',
    marginHorizontal: -16,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'SUIT-SemiBold',
    letterSpacing: -0.7,
    color: '#4B4B4B',
  },
  filterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterButton: {
    marginLeft: 12,
  },
  filterText: {
    fontSize: 12,
    fontFamily: 'SUIT-Medium',
    letterSpacing: -0.6,
    color: '#888888',
  },
  activeFilterText: {
    color: '#0D2525',
  },
  booksGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    paddingBottom: 20,
  },
});