import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    aiLoadingContainer: {
        width: 120,
        height: 120,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
        position: 'relative',
    },
    aiIconCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#F3FCF9',
        borderWidth: 2,
        borderColor: '#90D1BE',
        justifyContent: 'center',
        alignItems: 'center',
    },
    sparkle: {
        position: 'absolute',
    },
    sparkle1: {
        top: 10,
        right: 15,
    },
    sparkle2: {
        bottom: 15,
        left: 10,
    },
    sparkle3: {
        top: 20,
        left: 5,
    },
    loadingText: {
        fontSize: 16,
        fontFamily: 'SUIT-SemiBold',
        color: '#666',
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 8,
    },
    loadingSubText: {
        fontSize: 14,
        fontFamily: 'SUIT-Medium',
        color: '#90D1BE',
        textAlign: 'center',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 100,
    },
    emptyText: {
        fontSize: 18,
        fontFamily: 'SUIT-SemiBold',
        color: '#999999',
        marginTop: 16,
        textAlign: 'center',
    },
    emptySubText: {
        fontSize: 14,
        fontFamily: 'SUIT-Regular',
        color: '#CCCCCC',
        marginTop: 8,
        textAlign: 'center',
    },
    infoCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        height: 100,
        paddingHorizontal: 30,
        borderRadius: 20,
        borderWidth: 1.3,
        borderColor: '#90D1BE',
        marginTop: 25,
        marginBottom: 30,
        elevation: 5,
    },
    infoIcon: {
        marginRight: 15,
    },
    infoText: {
        flex: 1,
        fontSize: 16,
        fontFamily: 'SUIT-Medium',
        fontWeight: '500',
        color: '#666',
        letterSpacing: -0.4,
        lineHeight: 20,
    },
    roundedContainer: {
        backgroundColor: '#F3FCF9',
        borderTopLeftRadius: 40,
        borderTopRightRadius: 40,
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 32,
        marginHorizontal: -20,
    },
    section: {
        marginBottom: 32,
    },
    sectionHeader: {
        marginBottom: 16,
    },
    questionBadge: {
        backgroundColor: '#D8F3F1',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        alignSelf: 'flex-start',
        marginBottom: 8,
    },
    sectionQuestionContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        marginBottom: 4,
    },
    sectionQuestion: {
        fontSize: 13,
        fontWeight: '500',
        color: '#666666',
    },
    highlightTag: {
        backgroundColor: '#90D1BE40',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        marginRight: 4,
        marginBottom: 2,
        flexDirection: 'row',
        alignItems: 'center',
    },
    highlightText: {
        fontFamily: 'SUIT-SemiBold',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: -0.4,
        color: '#666666',
    },
    normalText: {
        fontFamily: 'SUIT-SemiBold',
        fontSize: 16,
        fontWeight: '500',
        letterSpacing: -0.4,
        color: '#666666',
    },
    sectionTitle: {
        fontFamily: 'SUIT-SemiBold',
        fontSize: 20,
        fontWeight: '600',
        letterSpacing: -0.45,
        color: '#0D2525',
    },
    bookCard: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        padding: 20,
        borderRadius: 16,
        shadowColor: '#90D1BE',
        shadowOffset: {
            width: 2,
            height: 2,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 4,
    },
    bookImagePlaceholder: {
        width: 90,
        height: 120,
        backgroundColor: '#F0F0F0',
        borderRadius: 8,
        marginRight: 18,
        overflow: 'hidden',
    },
    bookImage: {
        width: '100%',
        height: '100%',
    },
    bookInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    bookTitle: {
        fontFamily: 'SUIT-SemiBold',
        fontSize: 17,
        fontWeight: '600',
        color: '#0D2525',
        letterSpacing: -0.4,
        marginBottom: 8,
        lineHeight: 22,
    },
    bookAuthor: {
        fontFamily: 'SUIT-Medeum',
        fontSize: 15,
        color: '#666',
        fontWeight: '500',
        letterSpacing: -0.35,
        marginBottom: 8,
    },
    bookDescription: {
        fontFamily: 'SUIT-Medeum',
        fontSize: 15,
        color: '#666',
        fontWeight: '500',
        letterSpacing: -0.35,
        lineHeight: 20,
    },
    // 데이터 부족 카드 스타일 추가
    insufficientCard: {
        backgroundColor: '#FFFFFF',
        padding: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#90D1BE',
        shadowOffset: {
            width: 2,
            height: 2,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 4,
    },
    insufficientIconWrapper: {
        marginBottom: 16,
    },
    insufficientTitle: {
        fontFamily: 'SUIT-SemiBold',
        fontSize: 16,
        color: '#0D2525',
        marginBottom: 8,
        letterSpacing: -0.4,
    },
    insufficientMessage: {
        fontFamily: 'SUIT-Medium',
        fontSize: 14,
        color: '#999999',
        textAlign: 'center',
        marginBottom: 4,
        letterSpacing: -0.3,
    },
    insufficientSubMessage: {
        fontFamily: 'SUIT-Regular',
        fontSize: 13,
        color: '#CCCCCC',
        textAlign: 'center',
        letterSpacing: -0.3,
    },
});